### ISSUE TITLE
Error on periodic request

### ISSUE THREAD

**Issue by btsteve** [jros2300/reservedinstances#8]
I am getting this on the worker node. 
[2016-05-23T20:13:23.367950 #22356]  INFO -- : Started GET "/periodicworker" for 127.0.0.1 at 2016-05-23 20:13:23 +0000
F, [2016-05-23T20:13:23.369923 #22356] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/periodicworker"):
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  passenger (4.0.59) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.59) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'

**Comment by jros2300** [comment]
I've been testing the worker environment and it is working.

Please, can you create a full snapshot of the beanstalk logs and send them to me? (rosjavi@gmail.com)

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.logging.html

**Comment by btsteve** [comment]
Here you go. 
Thanks

[BundleLogs-1464108389181.zip](https://github.com/jros2300/reservedinstances/files/280011/BundleLogs-1464108389181.zip)
[BundleLogs-1464108374530.zip](https://github.com/jros2300/reservedinstances/files/280010/BundleLogs-1464108374530.zip)

**Comment by jros2300** [comment]
I don't see those errors in the logs, in any case I've uploaded a new version, can you redeploy the cloudformation template?

**Comment by btsteve** [comment]
Yes thanks, Will update you soon.
Thanks for the help.

**Comment by btsteve** [comment]
Still not getting any recommendations.

**Comment by jros2300** [comment]
So you're not getting any recommendation in the web, that's not related with the periodic job.

Do you see any line in the Summary in red?, are the instances in other AZ or instance type to move the unused RIs?

**Comment by btsteve** [comment]
So currently we do not have any reserve instances. We were hoping the tool
would make recommendations.

**Comment by btsteve** [comment]
WHen the s3importer tries to run i see this

I, [2016-05-25T14:07:59.262114 #3255]  INFO -- : Started POST "/s3importer"
for 127.0.0.1 at 2016-05-25 14:07:59 +0000
I, [2016-05-25T14:07:59.263881 #3255]  INFO -- : Processing by
SummaryController#s3importer as HTML
I, [2016-05-25T14:07:59.263929 #3255]  INFO -- :   Parameters:
{"summary"=>{}}
D, [2016-05-25T14:07:59.265900 #3255] DEBUG -- :   Setup Load (1.3ms)
 SELECT  `setups`.* FROM `setups`  ORDER BY `setups`.`id` ASC LIMIT 1
D, [2016-05-25T14:07:59.266253 #3255] DEBUG -- :   CACHE (0.0ms)  SELECT
 `setups`.* FROM `setups`  ORDER BY `setups`.`id` ASC LIMIT 1
D, [2016-05-25T14:07:59.266509 #3255] DEBUG -- :   CACHE (0.0ms)  SELECT
 `setups`.* FROM `setups`  ORDER BY `setups`.`id` ASC LIMIT 1
D, [2016-05-25T14:07:59.308135 #3255] DEBUG -- : Error
I, [2016-05-25T14:07:59.308400 #3255]  INFO -- :   Rendered text template
(0.0ms)
I, [2016-05-25T14:07:59.308586 #3255]  INFO -- : Completed 200 OK in 45ms
(Views: 0.3ms | ActiveRecord: 1.3ms)

**Comment by jros2300** [comment]
No,  the tool doesn't recommend new reserved instances, this tool helps to maintain the reserved instances used.

For recommendations you can use trusted advisor.

**Comment by btsteve** [comment]
Ok that that helps.

What format do you need to use for the DBR bucket name?
I has using dsad-dbr currently and it does not seen to be importing.
